---
- name: Update Inventory from OSPD
  hosts: undercloud
  gather_facts: yes
  any_errors_fatal: true
  vars:
      user: heat-admin
      # The var "private_key" is used outside this scope and cannot be overridden
      overcloud_pkey: "{{ inventory_dir }}/id_rsa_overcloud"
  tasks:
      - name: fetch the private key file from the undercloud
        fetch:
            src: "~/.ssh/id_rsa"
            dest: "{{ overcloud_pkey }}"
            flat: yes

      - name: update file permissions
        delegate_to: localhost
        become: no
        file:
            path: "{{ overcloud_pkey }}"
            mode: 0600

      - name: update IP of overcloud nodes
        vars:
            # Here can't be used {{ path_venv }}, because it's not a Jinja template
            ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
        os_server_facts:
            cloud: undercloud
            # Required for SSL
            validate_certs: no
        delegate_to: "{{ groups.shade | first }}"

      - name: add overcloud host
        include_tasks: ../tasks/add_overcloud_host.yml
        with_items: "{{ openstack_servers }}"
        loop_control:
            loop_var: node_info

      - name: list ironic nodes
        # Use CSV format as JSON not supported in old versions
        shell: |
            source ~/stackrc
            openstack baremetal {{ 'node' if install.version|default(undercloud_version)|openstack_release >= 10 else '' }} list -f csv
        register: ironic_node_list
        tags: skip_ansible_lint
        # Bug in Liberty version: No "node list" in openstack client, and no formatter in ironic client.
        when: install.version|default(undercloud_version)|openstack_release != 8


        # at this point we will have in inventory the openstack_node names
        # and they are often not alligned with the bm names. For example,
        # compute-2 OC node can correspond to the compute-1 bm node.
        # node will be marked as unused only when original_name(bm) does not
        # have instance uuid associated.

        # also need to handle the situation when oc node name is changed
        # (predictable hostnames and IPs feature)
        # in that case controller-0 bm can be renamed to ctrl-0 OC.
        # as the result the controller-0 node should be removed to the inventory
        # (and not added to the unused group)
        # and the ctrl-0 should be added with the original_name=controller-0
      - name: set ironic nodes fact
        vars:
            # take ironic UUID if name is missing
            - host_id: "{{ item.Name or item.UUID }}"
            # original name points to the baremetal name
            - host_original_name: "{{ hostvars.get(host_id, {}).original_name|default('') }}"
        set_fact:
            ironic_node_dict: "{{ ironic_node_dict|default({})|combine({ host_id: { 'original_name': host_original_name, 'instance_uuid': item['Instance UUID'] }}) }}"
            # Set empty list for Liberty version
        with_items: "{{  ironic_node_list.stdout|default('')|from_csv }}"
        when: host_id in groups.all

      - name: try to find unused nodes and add them into a new unused group
        with_dict: "{{ ironic_node_dict|default({}) }}"
        when:
            - item.key not in openstack_servers|map(attribute='name')|list
            - item.key in groups.all
            - (ironic_node_dict|default({})).get(item.value.original_name|default(''), item.value).instance_uuid|default('undefined') == ''
            - not install.splitstack|default(False)
        add_host:
            name: "{{ item.key }}"
            # groups can only be added
            groups: unused

      - block:
            - name: try to find unused nodes to scale and add them into a new unused group
              vars:
                  scale_node_name: "{{ install.node.name }}"
              when:
                  - scale_node_name not in openstack_servers|map(attribute='name')|list
                  - scale_node_name in groups.all
              add_host:
                  name: "{{ scale_node_name }}"
                  groups: unused
        when:
            - install.splitstack|default(False)
            - install.node.name is defined

      # Connection for baremetals must be forwarded through UC as OC nodes
      # lie on ctplane not accessible from anywhere else.
      # Done as "redundant" block because Ansible can not reference
      # one variable multiple times in block context.
      - block:
          - name: Enable SSH forwarding using UC node for baremetal OC nodes
            add_host:
                name: "{{ item.name }}"
                ansible_ssh_common_args: "-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                                          -W %h:%p -i {{ hostvars[groups['undercloud'][0]].ansible_ssh_private_key_file }} \
                                          {{ ssh_user }}@{{ ssh_host }}\""
            vars:
                ssh_user: "{{ hostvars[groups['undercloud'][0]].ansible_user | default(hostvars[groups['undercloud'][0]].ansible_ssh_user) }}"
                ssh_host: "{{ hostvars[groups['undercloud'][0]].ansible_host | default(hostvars[groups['undercloud'][0]].ansible_ssh_host) }}"
            when: "'hypervisor' not in groups"

            with_items: "{{ openstack_servers }}"

      - name: Enable SSH forwarding using hypervisor node for hybrid OC nodes
        add_host:
            name: "{{ item.name }}"
            ansible_ssh_common_args: " -o ForwardAgent=yes -o IdentitiesOnly=yes -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no \
                                       -o UserKnownHostsFile=/dev/null -o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                                       -W %h:%p -i {{ hostvars[groups['undercloud'][0]].ansible_ssh_private_key_file }} \
                                          {{ ssh_user }}@{{ ssh_host }}\""
        vars:
            ssh_user: "{{ hostvars['hypervisor'].ansible_user | default(hostvars['hypervisor'].ansible_ssh_user) }}"
            ssh_host: "{{ hostvars['hypervisor'].ansible_host | default(hostvars['hypervisor'].ansible_ssh_host) }}"
        when:
          - "'hypervisor' in groups"
          - install.hybrid|default(false)

        with_items: "{{ openstack_servers }}"


- name: generate inventory file
  hosts: localhost
  gather_facts: no
  tags: always
  roles:
      - role: inventory-update
        omit_hosts: "{{ hostvars[groups['undercloud'][0]].nodes_to_delete|default([])|difference(hostvars[groups['undercloud'][0]].nodes_added|default([]))|difference(groups.get('unused', [])) }}"