---
# Iterate over existing cinder backends, configuring matching volume types.
# Set backend for the default tripleo volume type.

- name: Cinder backend config
  hosts: undercloud

  tasks:
    - name: Detect existing Cinder backends
      shell: |
          source ~/{{ install.overcloud.stack }}rc
          cinder get-pools --detail | awk '/volume_backend_name/{print $4}'
      register: backend_list
      ignore_errors: true

    - name: Create volume types to fit backends
      shell: |
          source ~/{{ install.overcloud.stack }}rc
          cinder type-show "{{ item }}" &>/dev/null || cinder type-create "{{ item }}"
      loop: "{{ backend_list.stdout_lines }}"
      ignore_errors: true

    - name: Configure backend names per volume types
      shell: |
          source ~/{{ install.overcloud.stack }}rc
          cinder type-key "{{ item }}" set volume_backend_name="{{ item }}"
      loop: "{{ backend_list.stdout_lines }}"

    - name: Set triple's volume type backend if defined
      shell: |
          source ~/{{ install.overcloud.stack }}rc
          cinder type-key tripleo set volume_backend_name={{ install.cinder.tripleo.volume.backend }}
      when: install.cinder.tripleo.volume.backend is defined
