---
- name: Create customized flavors
  hosts: undercloud
  gather_facts: no
  tasks:
      - name: Create compute flavors
        os_nova_flavor:
            cloud: overcloud
            state: present
            name: "{{ item.name }}"
            ram: "{{ install.workload.memory }}"
            vcpus: "{{ install.workload.vcpu }}"
            disk: "{{ install.workload.disk }}"
            flavorid: "{{ item.flavorid }}"
        loop:
            - { name: customized_flavor, flavorid: "{{ install.workload.flavorid }}" }
            - { name: customized_flavor_alt, flavorid: "{{ (install.workload.flavorid|int + 1 )|string }}" }
        register: customized_flavor

      - name: Save customized flavors for registration
        set_fact:
            flavors_custom: "{{ customized_flavor.flavor }}"
