---
- name: Create customized flavors and image
  hosts: undercloud
  gather_facts: no
  tasks:
      - name: Create compute flavors
        vars:
            ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
        os_nova_flavor:
            cloud: overcloud
            state: present
            name: "{{ item.name }}"
            ram: "{{ install.workload.memory }}"
            vcpus: "{{ install.workload.vcpu }}"
            disk: "{{ install.workload.disk }}"
            flavorid: "{{ item.flavorid }}"
        loop:
            - { name: customized_flavor, flavorid: "{{ install.workload.flavorid }}" }
            - { name: customized_flavor_alt, flavorid: "{{ (install.workload.flavorid|int + 1 )|string }}" }
        delegate_to: "{{ groups.shade | first }}"

      - name: Create image
        block:
            - name: Download image
              get_url:
                  url: "{{ install.image }}"
                  dest: /tmp/image.qcow2
            - name: Set hostname url
              set_fact:
                  hostname_url: "{{ install.image | basename }}"
            - name: Upload {{ hostname_url }} image
              shell: |
                source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
                openstack image create {{ hostname_url }} --disk-format qcow2 --container-format bare --file /tmp/image.qcow2
        when: install.image is defined

