---
- name: Create customized flavors and image
  hosts: undercloud
  gather_facts: no
  tasks:
      - name: Create compute flavors
        vars:
            ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
        os_nova_flavor:
            validate_certs: no
            cloud: overcloud
            state: present
            name: "{{ item.name }}"
            ram: "{{ install.workload.memory }}"
            vcpus: "{{ install.workload.vcpu }}"
            disk: "{{ install.workload.disk }}"
            flavorid: "{{ item.flavorid }}"
            extra_specs: "{{ install.workload.flavor.extra.specs }}"
        loop:
            - { name: customized_flavor, flavorid: "{{ install.workload.flavorid }}" }
            - { name: customized_flavor_alt, flavorid: "{{ (install.workload.flavorid|int + 1 )|string }}" }
        delegate_to: "{{ groups.shade | first }}"

      - name: Create image
        block:
            - name: Set hostname url
              set_fact:
                  hostname_url: "{{ install.image | basename }}"
            - name: Download image
              get_url:
                  url: "{{ install.image }}"
                  dest: "/tmp/{{ hostname_url }}"
            - name: Upload {{ hostname_url }} image
              shell: |
                  source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
                  openstack image create {{ item.name }} --disk-format qcow2 --container-format bare --file /tmp/{{ hostname_url }} --public
              loop:
                - { name: "{{ hostname_url }}" }
                - { name: "{{ hostname_url }}_alt" }
            - name: Upload {{ hostname_url }} image with extra specs
              shell: |
                  source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
                  openstack image set {{ hostname_url }} --property {{ item }}
                  openstack image set {{ hostname_url }}_alt --property {{ item }}
              loop: "{{ install.workload.image.get('properties', []) }}"
              when: install.workload.image.properties is defined
        when: install.image is defined
        ignore_errors: yes
