---
- import_playbook: ../service_discovery.yml
  vars:
      services: ['nova-scheduler']

- name: Launch workload
  hosts: undercloud
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Check if /var/lib/config-data/puppet-generated/nova/etc/nova/nova.conf exists
      stat:
          path: /var/lib/config-data/puppet-generated/nova/etc/nova/nova.conf
      register: nova_conf_is_containerize
      delegate_to: "{{ groups.nova_scheduler | first }}"

    - name: Set nova.conf path
      set_fact:
          nova_conf: "{{ nova_conf_is_containerize.stat.exists|ternary('/var/lib/config-data/puppet-generated/nova/etc/nova/nova.conf', '/etc/nova/nova.conf') }}"

    - name: Install crudini package
      package:
          name: crudini
          state: present
      delegate_to: "{{ groups.nova_scheduler | first }}"
      become: yes
      
    - name: get the default floating ip pool name from the server
      shell: |
              crudini --get {{ nova_conf }} neutron default_floating_pool || \
              grep -oP "(?<=default_floating_pool=)(.*$)" {{ nova_conf }} || \
              awk -F'\"' '/default_floating_pool/ {print $4}' /etc/puppet/hieradata/service_configs.json
      register: pool_name
      delegate_to: "{{ groups.nova_scheduler | first }}"
      changed_when: false
      become: yes

    - name: Update quotas RHOS-10+
      shell: |
        source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
        # w/a bz1780787:
        unset OS_COMPUTE_API_VERSION
        openstack quota set --cores -1 --instances -1 --volumes -1 \
                    --networks -1 --subnets -1 --ports -1 --routers -1 \
                    --ram -1 --secgroups -1 --fixed-ips -1 \
                    --floating-ips -1 admin
      when: install.version|default(undercloud_version)|openstack_release > 9

    - name: Update quotas RHOS<10
      shell: |
          source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
          openstack quota set --cores -1 --instances -1 --volumes -1 \
                    --ram -1 --secgroups -1 --fixed-ips -1 \
                    --floating-ips -1 admin
      when: install.version|default(undercloud_version)|openstack_release < 10

    - include_tasks: ../tasks/launch_workload_step.yml
      loop_control:
          loop_var: step
      with_sequence: start=0 end={{ install.workload.index|int - 1 }}
