---
- name: Launch workload
  hosts: undercloud
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - include: launch_workload_step.yml
      loop_control:
          loop_var: step
      with_sequence: start=0 end={{ install.workload.index }}|int - 1
