---
- name: Launch workload
  hosts: undercloud
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Update quotas RHOS-10+
      shell: |
          source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
          openstack quota set --cores -1 --instances -1 --volumes -1 \
                    --networks -1 --subnets -1 --ports -1 --routers -1 \
                    --ram -1 --secgroups -1 --fixed-ips -1 \
                    --floating-ips -1 admin
      when: install.version > 9

    - name: Update quotas RHOS<10
      shell: |
          source {{ ansible_user_dir }}/{{ install.overcloud.stack }}rc
          openstack quota set --cores -1 --instances -1 --volumes -1 \
                    --ram -1 --secgroups -1 --fixed-ips -1 \
                    --floating-ips -1 admin
      when: install.version < 10

    - include_tasks: ../tasks/launch_workload_step.yml
      loop_control:
          loop_var: step
      with_sequence: start=0 end={{ install.workload.index|int - 1 }}
