- name: Check and correct time diff after deployment on controllers
  hosts: controller
  become: true
  gather_facts: no
  any_errors_fatal: true
  tasks:
      - name: clockdiff to each peer before forced ntp sync.
        shell: |
            extra_log_root=/var/log/extra
            mkdir -p "$extra_log_root"
            time_log="${extra_log_root}/clockdiff_before"
            echo -n "date:" >"$time_log"
            date &>>"$time_log"
            {% for host in groups['all'] %}
            # something that applies to all app servers.
            {% if 'ansible_default_ipv4' in hostvars[host] %}
            echo -n {{ host }} [{{ hostvars[host]['ansible_default_ipv4']['address'] }}] ": " &>>"$time_log"
            clockdiff {{ hostvars[host]['ansible_default_ipv4']['address'] }} &>>"$time_log"
            {% endif %}
            {% endfor %}
        failed_when: false
        changed_when: false
        tags: skip_ansible_lint

      - name: ntp sync.
        shell: |
          {% if install.version|default(hostvars[groups['undercloud'] | first]['undercloud_version']) | openstack_release < 15 %}
          ntpdate -bu -p 8 {{ install.ntp.server }} && hwclock -w
          {% else %}
          chronyc waitsync 20 && hwclock -w
          {% endif %}

        register: ntp_sync_out
        ignore_errors: true

      - debug:
           msg: "ntp sync: out:{{ntp_sync_out.stdout}} err:{{ntp_sync_out.stderr}}"
        ignore_errors: true

      - name: clockdiff to each peer after ntp sync.
        shell: |
            extra_log_root=/var/log/extra
            mkdir -p "$extra_log_root"
            time_log="${extra_log_root}/clockdiff_after"
            echo -n "date:" >"$time_log"
            date &>>"$time_log"
            {% for host in groups['all'] %}
            # something that applies to all app servers.
            {% if 'ansible_default_ipv4' in hostvars[host] %}
            echo -n {{ host }} [{{ hostvars[host]['ansible_default_ipv4']['address'] }}] ": " &>>"$time_log"
            clockdiff {{ hostvars[host]['ansible_default_ipv4']['address'] }} &>>"$time_log"
            {% endif %}
            {% endfor %}
        ignore_errors: true
        tags: skip_ansible_lint
