- name: Gather facts for Hypervisor
  hosts: hypervisor
  gather_facts: yes
  any_errors_fatal: true

- name: Gather facts for Overcloud Nodes
  hosts: overcloud_nodes:!unused
  gather_facts: no
  any_errors_fatal: true
  tasks:
      - block:
            - name: apply node hostnames
              hostname:
                  name: "{{ inventory_hostname }}"

            - setup:

        when: install.splitstack|default(False)

- name: Scale up
  hosts: undercloud
  gather_facts: yes
  any_errors_fatal: true
  vars:
      # overcloud deployment script
      overcloud_deploy_script: "~/overcloud_deploy.sh"
      # new instackenv file
      instackenv_file_name: "~/newnodes.json"
      # vbmc start port
      vbmc_start_port: 6230
      # undercloud keys
      local_undercloud_pubkey: "{{ inventory_dir }}/id_rsa_undercloud.pub"
      default_privatekey: "~/.ssh/id_rsa"
      default_pubkey: "{{ default_privatekey }}.pub"
      # rhos-release vars
      tmp_oc_repos_dir: /tmp/oc_repos/yum.repos.d
      rhos_release_rpm: "https://url.corp.redhat.com/rhos-release-latest-rpm"
  tasks:
      - name: Scale up validation
        include_tasks: ../tasks/scale/up/validation.yml

      - block:
            - name: Prepare splitstack nodes
              include_tasks: ../tasks/scale/up/splitstack/prepare_nodes.yml
              delegate_to: "{{ item }}"
              become: true
              with_items: "{{ install.scale.nodes }}"

            - name: Run heat agent script
              include_tasks: ../tasks/scale/up/splitstack/heat_agent_install.yml

            - name: Scale up splitstack install
              include_tasks: ../tasks/scale/up/splitstack/templates_update.yml

        when: install.splitstack|default(False)

      - name: Scale up normal install
        include_tasks: ../tasks/scale/up/normal_flow.yml
        when: not install.splitstack|default(False)

      - name: Print deploy command
        command: "cat {{ overcloud_deploy_script }}"

      - name: Execute the overcloud deploy script
        shell: |
            source ~/stackrc
            bash {{ overcloud_deploy_script }} &> overcloud_scale_up.log
        register: overcloud_scale
        ignore_errors: yes

      - name: Print the last few lines of the output to spot failures
        command: tail -n60 overcloud_scale_up.log

      - name: Print stack failures
        shell: |
            source ~/stackrc
            openstack stack failures list {{ install.overcloud.stack }} --long 2>&1 | tee openstack_failures_scale_up.log
        when: overcloud_scale.rc != 0 and undercloud_version|openstack_release >= 10
        tags: skip_ansible_lint

- name: Try to update inventory even when deployment has failed
  import_playbook: add_overcloud_hosts.yml
  tags:
      - inventory_update

- name: Verify overcloud scale up
  hosts: undercloud
  gather_facts: no
  any_errors_fatal: true
  tasks:
      - fail:
            msg: "Overcloud scale up failed... :("
        when:
            - overcloud_scale is defined
            - overcloud_scale.rc != 0
