# run stages
rc_preliminary_checks: yes
rc_perform_undercloud_db_backup: yes
rc_remove_ceph_monitor: yes
rc_replace_node: yes
rc_manual_preparation: yes
rc_manual_intervention: yes
rc_finalize: yes

# specifies whether the controller is reachable by ssh or not
rc_controller_is_reachable: yes

# specifies if role should fail when replacement was not successful.
# default is 'no' to make sure we can update inventory after failed replacement.
rc_fail_on_replace: no

rc_valid_controller_nodes: "{{ groups.controller|difference(groups.get('unused', []))|difference([install.controller.to.remove, install.controller.to.add]) }}"
rc_corosync_retries: 5
overcloud_deploy_script: "~/overcloud_deploy.sh"

# new instackenv file
instackenv_file_name: "~/newnodes.json"
# old instackenv file
orig_instackenv_file_name: "~/instackenv.json"

# the timeout to wait while adding new controller to the cluster
# may work workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1600169
# by checning it from 0 to 1000.
rc_cluster_node_add_wait: 0

# set correct container runtime
container_runtime: "{{ (install.version | default(undercloud_version) | openstack_release > 14) | ternary('podman', 'docker') }}"

#set correct nova service
nova_compute_service: "{{ (install.version | default(undercloud_version) | openstack_release > 14) | ternary('tripleo_nova_compute', 'openstack-nova-compute') }}"

