# need to use raw module here, because with shell and command the 'ceph' command
# cannot be found

- name: Set container cli for <= OSP14
  set_fact:
    _container_cli: docker
  when: install.version|default(undercloud_version)|openstack_release <= 14

- name: Set container cli for >= OSP15
  set_fact:
    _container_cli: podman
  when: install.version|default(undercloud_version)|openstack_release >= 15


- name: get mon stats
  command: "{{ _container_cli }}" exec -it ceph-mon-{{ ansible_hostname }} ceph mon stat"
  become: true
  register: ceph_mon_stat
  delegate_to: "{{ rc_valid_controller_nodes|first }}"

- name: get ip address of the monitor to remove
  set_fact:
      controller_remove_ip: "{{ ceph_mon_stat.stdout | regex_replace('.*' + install.controller.to.remove + '=([0-9\\.]*):.*', '\\1') }}"
  when: install.controller.to.remove in ceph_mon_stat.stdout

- name: remove mon service
  block:
      - name: stop mon service
        command: "systemctl stop ceph-mon@{{ install.controller.to.remove }}"
        delegate_to: "{{ install.controller.to.remove }}"
        when: rc_controller_is_reachable

      - name: remove the monitor from the cluster
        command: "{{ _container_cli }} exec -it ceph-mon-{{ ansible_hostname }} ceph mon remove {{ install.controller.to.remove }}"
        when: install.controller.to.remove in ceph_mon_stat.stdout
        delegate_to: "{{ rc_valid_controller_nodes|first }}"
        become: no

      - name: remove monitor entry from /etc/ceph/ceph.conf
        replace:
            path: /etc/ceph/ceph.conf
            regexp: '{{ install.controller.to.remove }}(,)?'
        delegate_to: "{{ item }}"
        with_items: "{{ rc_valid_controller_nodes }}"

      - name: remove monitor ip entry from /etc/ceph/ceph.conf
        replace:
            path: /etc/ceph/ceph.conf
            regexp: "{{ controller_remove_ip }}(,)?"
        delegate_to: "{{ item }}"
        with_items: "{{ rc_valid_controller_nodes }}"
        when: controller_remove_ip is defined
  become: yes
